### PR TITLE
Resource Usage Module

### PR DESCRIPTION
**Pull request by nicholas-eden**
Added a module to display CPU, memory, and swap usage.  Altered the Bar Graph chart to better fit what I had in mind to display the usage. 

This is partially for #288.  I'm not sure if there is a way to run htop within a widget, but this is a pretty easy alternative.

resource usage

Nothing fancy on the config:
```
    resourceusage:
      enabled: true
      position:
        top: 0
        left: 0
        width: 1
        height: 1
      refreshInterval: 1
```

### CODE REVIEW

**Comment by nicholas-eden** [comment]
I'll fix up the tests, comment if you see anything you don't like.

**Comment by nicholas-eden** [comment]
Yeah, it's currently Linux only.  I'm looking at how to make it cross-platform.  This lib has potential https://github.com/shirou/gopsutil

**Comment by nicholas-eden** [comment]
I switched over to using gopsutil since it has windows support built in.  I'll try to test on other platforms to see if it works.

**Comment by senorprogrammer** [comment]
Unfortunately under MacOS this branch currently crashes:
```
panic: strings: negative Repeat count
goroutine 71 [running]:
strings.Repeat(0x4ab899a, 0x1, 0xe666666666666600, 0x0, 0x0)
/usr/local/Cellar/go/1.11.1/libexec/src/strings/strings.go:543 +0x1e3
github.com/senorprogrammer/wtf/wtf.BuildStars(0xc000708000, 0xe, 0xe, 0x14, 0x4ab899a, 0x1, 0xc0003c4d80, 0xc0005660c0)
/Users/ccummer/go/src/github.com/senorprogrammer/wtf/wtf/bargraph.go:158 +0x25f
github.com/senorprogrammer/wtf/wtf.(*BarGraph).BuildBars(0xc00002f320, 0xc000708000, 0xe, 0xe)
/Users/ccummer/go/src/github.com/senorprogrammer/wtf/wtf/bargraph.go:118 +0x63
github.com/senorprogrammer/wtf/resourceusage.MakeGraph(0xc00002f320)
/Users/ccummer/go/src/github.com/senorprogrammer/wtf/resourceusage/widget.go:92 +0x7e5
github.com/senorprogrammer/wtf/resourceusage.display(0xc00002f320)
/Users/ccummer/go/src/github.com/senorprogrammer/wtf/resourceusage/widget.go:112 +0x2b
github.com/senorprogrammer/wtf/resourceusage.(*Widget).Refresh(0xc00002f320)
/Users/ccummer/go/src/github.com/senorprogrammer/wtf/resourceusage/widget.go:105 +0x7e
github.com/senorprogrammer/wtf/wtf.Schedule(0x4ca7300, 0xc00002f320)
/Users/ccummer/go/src/github.com/senorprogrammer/wtf/wtf/scheduler.go:14 +0x49
```

**Comment by nicholas-eden** [comment]
Thanks.  That might be resolved.  Reading the CPU usage percent seems less than perfectly reliable.  Negative values and values over 100 crash the chart. 

The gopsutil lib isn't currently able to read the cpu percent for windows, but I think that will be resolved soon.  I think I have an idea on how to fix it if there isn't already an open pull request.

**Comment by nicholas-eden** [comment]
I've got my wife's macbook up and running with go.  The problem seems to still exist.

**Comment by nicholas-eden** [comment]
Fixed now, looks good on mac.

**Comment by senorprogrammer** [comment]
That's pretty sweet, nice work!

**Pull request merged**
