### PR TITLE
Go modules

### PR DESCRIPTION
**Pull request by retgits**
# Changes to adopt Go modules

Original GH issue: #406

## README

* Updated readme to reflect the use of modules

## Gopkg

* Removed `Gopkg.toml` and `Gopkg.lock`

## Go mods

* Created `go.mod` and `go.sum` which replaced `Gopkg.toml` and `Gopkg.lock`

## Vendor

* Removed `vendor` folder
* Vendor folder could be recreated using `go mod vendor`

## Makefile

* Added GO111MODULE and GOPROXY variables
* Updated `size` target to no longer look at .toml files and vendor folder (because they no longer exist)

## Travis CI

* Added GO111MODULE and GOPROXY variables
* Travis CI build works correctly: https://travis-ci.com/retgits/wtf/builds/109823752 and https://travis-ci.com/wtfutil/wtf/builds/109823954

## GitHub module

* Replaced import path to match instructions on https://github.com/google/go-github

## Tests run

```bash
sudo rm -rf $GOPATH/pkg/mod
make build
# results in a correct wtf executable
```

```bash
sudo rm -rf $GOPATH/pkg/mod
go get ./... && go get github.com/go-test/deep && go test -v github.com/wtfutil/wtf/wtf_tests/...
# results in all tests passing
```

The `sudo rm -rf $GOPATH/pkg/mod` makes sure that the local go modules cache is completely gone and we properly test the use of Go modules downloaded from the GoCenter proxy

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Awesome. To get this to work I first had to do: `export GO111MODULE=on`.

Currently it fails with the following error:
```
❯ go build
go: finding github.com/StackExchange/wmi v0.0.0-20180116203802-5d049714c4a6
go: finding github.com/alecthomas/chroma v0.6.2
...
go: finding github.com/mattn/go-colorable v0.0.9
verifying github.com/go-ole/go-ole@v1.2.2/go.mod: checksum mismatch
	downloaded: h1:pnvuG7BrDMZ8ifMurTQmxwhQM/odqm9sSqNe5BUI7v4=
	go.sum:     h1:7FAglXiTm7HKlQRDeOQ6ZNUHidzCWXuZWq/1dTyBNF8=
```

Thoughts?

**Comment by retgits** [comment]
Good point, should we add to the docs or README that if you want to build from the sources you need to set `GO111MODULE=on` if you're running the `go build` command from your `$GOPATH`? If you're not building the source from within your `$GOPATH` you shouldn't see that issue.

I've set my `GOPROXY` to `GOPROXY="https://gocenter.io"`, which makes sure I get the modules from GoCenter as opposed to downloading the sources from GitHub and building the modules locally. I could replicate the behavior by removing the GOPROXY environment variable.

```bash
export GOPROXY=""
go build
...
verifying github.com/go-ole/go-ole@v1.2.2/go.mod: checksum mismatch
        downloaded: h1:pnvuG7BrDMZ8ifMurTQmxwhQM/odqm9sSqNe5BUI7v4=
        go.sum:     h1:7FAglXiTm7HKlQRDeOQ6ZNUHidzCWXuZWq/1dTyBNF8=
```

and after setting it

```bash
export GOPROXY="https://gocenter.io"
go build
# works fine :)
```

Should I add that as a comment to the README?

**Comment by senorprogrammer** [comment]
Ah, I should have thought of that. I do think that should be in the README. I suspect the majority of people will still be building from within the GOPATH, given that that's likely where they'll still be pulling to when updating.

It's building for me now - nice work! I appreciate this quite a bit.

**Comment by retgits** [comment]
Cool! Let me add those two things to the README :)

**Comment by retgits** [comment]
Added both comments to the README

**Pull request merged**
