### PR TITLE
Fix textWidget.tpl and add message to facilitate module creation

### PR DESCRIPTION
**Pull request by Quentinchampenois**
Hello

#### Description

I found a configuration issue in the module textWidget generator template. 

**[ENHANCEMENT]**

I suggest to add a simple message after module generation because even in documentation I didn't found any information about my widget that is not recognized in my dashboard. 

Let me know if you have any question.
Thank you and thanks for this tool !

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Good idea!

**Comment by Quentinchampenois** [comment]
Hi, thank you 

I just saw that the CI is broken, my bad. I convert this PR to draft, and re-open it when it is fixed.

I just have a question, instructions [defined in documentation](https://wtfutil.com/development/creating_new_modules/) didn't work for me when trying to generate a new module. 
The solution I found is to use command `WTF_WIDGET_NAME="my_module" go run generator/textwidget.go`,  is the documentation deprecated or maybe I forgot a step to generate my module using `WTF_WIDGET_NAME=MyNewWidget go generate -run=text` ?

**Comment by senorprogrammer** [comment]
You're right about that, and I don't know why that has changed. The generator code has been largely unmaintained, the change here was definitely not deliberate.

**Comment by senorprogrammer** [comment]
The imports failure is not because of your changes. I should have a fix for those failures shortly.

**Comment by senorprogrammer** [comment]
Alright, this should be fixed now. If you rebase your branch off of `master`, everything should now pass.

**Comment by Quentinchampenois** [comment]
Hello, 

I have rebased my branch. Are you interested by an update of the module documentation ?

**Comment by senorprogrammer** [comment]
Yes, absolutely, that would be great.

**Pull request merged**
