### PR TITLE
Blank import time/tzdata to fix clocks module on Windows

### LINKED ISSUE #994: Clocks module "no timezone data available"
I'm struggling with _sample_configs/sample_config.yml...the clocks modules only show me "no timezone data available". I've also tried replacing one of the modules in the config with the YAML from the clocks module documentation ( https://wtfutil.com/modules/clocks/ )...same result. (Windows host, "running via docker" flavor, mapping _sample_configs/sample_config.yml into container's default config location with -v "$(pwd)/_sample_configs/sample_config.yml:/config/.config/wtf/config.yml").

My sample_config.yml is straight from the master branch. My clocks look like this:
```
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    europe_time:
      title: "Europe"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        GMT: "Etc/GMT"
        Amsterdam: "Europe/Amsterdam"
        Berlin: "Europe/Berlin"
        Barcelona: "Europe/Madrid"
        Copenhagen: "Europe/Copenhagen"
        London: "Europe/London"
        Rome: "Europe/Rome"
        Stockholm: "Europe/Stockholm"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    americas_time:
      title: "Americas"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        UTC: "Etc/UTC"
        Vancouver: "America/Vancouver"
        New_York: "America/New_York"
        Sao_Paulo: "America/Sao_Paulo"
        Denver: "America/Denver"
        Iqaluit: "America/Iqaluit"
        Bahamas: "America/Nassau"
        Chicago: "America/Chicago"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
```
```bash
trimble@logan MINGW64 ~/workspace/wtf (master)
$ MSYS_NO_PATHCONV=1 docker run -it -v "$(pwd)/_sample_configs/sample_config.yml:/config/.config/wtf/config.yml" wtfutil
```
image

Spitballing: something weird with line endings/encoding/formatting?

### PR DESCRIPTION
**Pull request by trimble**
Resolves #994 

Windows hosts have issues fetching time zone location info (see https://github.com/golang/go/issues/38453). Therefore, the clocks module does not display any time info, only the "no timezone data available" error message.

Golang 1.15 introduced a blank import of time/tzdata that packs the necessary info into the executable (https://golang.org/doc/go1.15#time/tzdata).

Importing this new module in main.go fixes the "no timezone data available" issue on Windows hosts.

NOTE: there is also an option to include the tzdata with a build tag instead of the blank include. I think the blank include is easier to search info for, and therefore more straightforward. But, I'm open to other opinions on that.

### CODE REVIEW

**Comment by trimble** [comment]
Well, I guess I'll figure out how to make the static checker happy...

**Comment by senorprogrammer** [comment]
According to the [package info](https://golang.org/pkg/time/tzdata/): `This package should normally be imported by a program's main package, not by a library` so where you have it makes sense. 

Curious about that CI error you're getting. I wonder if it's because `golang-github-actions` is running `FROM golang:1.13.4`.

**Comment by senorprogrammer** [comment]
I just updated the CI tooling to use Go 1.15.2. Want to merge `master` into your branch, push it back up here, and see if that helps?

**Comment by senorprogrammer** [comment]
One thought: want to drop a comment into `main.go` above this change explaining why it's there? As it stands now, it'll look strange to anyone not familiar with the underlying issue.

**Comment by trimble** [comment]
> One thought: want to drop a comment into `main.go` above this change explaining why it's there? As it stands now, it'll look strange to anyone not familiar with the underlying issue.

Will do. Thanks for helping sort this out!

**Comment by trimble** [comment]
Works!

image

**Comment by senorprogrammer** [comment]
That's awesome!

**Pull request merged**
