### PR TITLE
Migrate all modules to their own subfolder

### PR DESCRIPTION
**Pull request by Seanstoppable**
Handles #375

### CODE REVIEW

**Comment by Seanstoppable** [comment]
I figured the more modules that are created, the more tedious this is going to be. Since I have a few modules I want to create, seems easier to migrate now.

**Comment by senorprogrammer** [comment]
This is great. I'll merge this in as soon as I can.

**Comment by E3V3A** [comment]
Great! :)

**Comment by senorprogrammer** [comment]
Awesome, thanks for this.

**Pull request merged**
