### PR TITLE
Improve bargraph view so bar colors are configurable

### PR DESCRIPTION
**Pull request by Seanstoppable**
Inspired by #624
Update the view object so that widget developers can configure bar color

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Specs are failing. Looks like it's missing a default value.

**Comment by Seanstoppable** [comment]
Expanded/fixed the test. In the case where a value isn't set, it will use whatever other coloring is set.
Example:

Screen Shot 2019-09-13 at 7 24 44 PM

**Comment by senorprogrammer** [comment]
I think it should not be rendering `[[]|||` though, the `[[]` set of braces is left over because the colour is not defined inside them, so they're rendering. `white` should probably be written in there, or the braces removed.

**Comment by senorprogrammer** [comment]
👍

**Pull request merged**
