### PR TITLE
Wicd

### PR DESCRIPTION
**Pull request by alexfornuto**
This depends on #584 

This change pulls the Wireless encryption method from wicd instead of nmcli. It **Should Not** be merged as is, since many more systems are using NetworkManager than wicd.

I am not a developer, but I figured out this much. I'm hoping that some generous soul will ammend this PR with the Go code making this an elif statement such that if the nmcli output is a failure, it will try this code instead.

With such an elif in place, others could further expand this section to use their networking client of choice.

### CODE REVIEW

**Comment by senorprogrammer** [comment]
This is an interesting idea. I'd like other knowledgable Linux users to weigh in on the ideas in here.

**Comment by dasJ** [comment]
Any reason /usr/bin is hardcoded? The path is usually in $PATH and I don't see any reason to limit us here.

**Comment by alexfornuto** [comment]
IIRC that had to do with me not finding the command in either my PATH or in bash completion. Now that hacktoberfest is upon us, I hope to be looking at this again soon.

**Comment by senorprogrammer** [comment]
Any thoughts on continuing this PR?

**Comment by alexfornuto** [comment]
IIRC correctly what it needs is a check to see if nmcli is present. Not sure how to GO that, but I'll give it a look this weekend.

**Comment by senorprogrammer** [comment]
Closing this out due to inactivity. Feel free to reopen if anything changes.

**Pull request closed without merging**
