### PR TITLE
Modular modules

### PR DESCRIPTION
**Pull request by jalavosus**
Implement a semi-sane setup for loading custom modules **at runtime** using go's `plugin` package and shared library linking. 

Within the `pluggable` directory lies a dragon named `ExternalModule`, an interface with the single function definition `Initialize`. A modular module implementing `Initialize()` properly will set itself up all nice and pretty, and return a fully ready-to-use widget. 

Somehow, this whole setup works more simply than I thought it would in my head. 

This can be tested out using the contents of the `example_pluggable` directory. All one needs to do is
- Make sure they've run `make build` so that the updated `MakeWidget` function is built 
- Run the `compile_module.sh` script found in `pluggable/example_pluggable` so that the example modular module is built and its shared object library is output somewhere
- Run `./bin/wtfutil --config="./pluggable/example_pluggable/test_config.yml"`

Result:
Screen Shot 2021-08-19 at 12 46 21

Please change the names of some of these functions/structs/etc., I wrote this on 6 hours of sleep while traveling on Amtrak.

### CODE REVIEW

**Comment by senorprogrammer** [comment]
This looks pretty coo! I'm on vacation right now (and on my phone) but as soon as I get back I'll dig into it further. Nice work.

(The build error above can probably be fixed by running `go mod tidy`).

**Comment by senorprogrammer** [comment]
One question: as far as I know, plugins in Go are currently unsupported and don't work on Windows. Has that changed? Any solution that would be added to WTF would need to support Windows as well.

**Comment by senorprogrammer** [comment]
This is definitely the direction I want WTF to be going. Having to compile every module whether you need them or not is not ideal, however any solution needs to also either a) support Windows users, or b) fall back to "compile all" for Windows users. We can't leave them behind.

This approach (or something similar) is interesting https://github.com/hashicorp/go-plugin but I suspect would require a pretty major re-write of all the plugins.

**Comment by jalavosus** [comment]
@senorprogrammer Sorry it's taken me so damn long to get around to this.

I just pushed a really whack commit (https://github.com/wtfutil/wtf/pull/1099/commits/48aafcc82bddbb029dd81e9ddb5c61531d19b937)  which shows some basic implementation of hashicorp/go-plugin's system. 

The idea here is to make it so that nothing from the core code has to be rewritten, and to make it so that external modules can just kinda be passed around and used willy-nilly. 

I haven't tested it yet, but will get to it at some point.

**Comment by jalavosus** [comment]
Can't say I've ever seen this sort of error before:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff203dec9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff203dec9e
stack: frame={sp:0x7ffeefbff298, fp:0x7ffeefbff2e8} stack=[0x7ffeefb80338,0x7ffeefbff3a0)
0x00007ffeefbff198:  0x01007ffeefbff1b8  0x0000000000000004
0x00007ffeefbff1a8:  0x000000000000001f  0x00007fff203dec9e
0x00007ffeefbff1b8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff1c8:  0x0000000004038131 <runtime.throw+0x0000000000000071>  0x00007ffeefbff268
0x00007ffeefbff1d8:  0x000000000585ac25  0x00007ffeefbff220
0x00007ffeefbff1e8:  0x00000000040383e8 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000006d82800
0x00007ffeefbff1f8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff208:  0x00007ffeefbff268  0x0000000004038131 <runtime.throw+0x0000000000000071>
0x00007ffeefbff218:  0x0000000006d82800  0x00007ffeefbff258
0x00007ffeefbff228:  0x0000000004038370 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff238
0x00007ffeefbff238:  0x00000000040383a0 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000006d82800
0x00007ffeefbff248:  0x0000000004038131 <runtime.throw+0x0000000000000071>  0x00007ffeefbff268
0x00007ffeefbff258:  0x00007ffeefbff288  0x0000000004038131 <runtime.throw+0x0000000000000071>
0x00007ffeefbff268:  0x00007ffeefbff270  0x0000000004038160 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff278:  0x000000000587658f  0x000000000000002a
0x00007ffeefbff288:  0x00007ffeefbff2d8  0x000000000404e8b6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff298: <0x000000000587658f  0x000000c00007acc0
0x00007ffeefbff2a8:  0x00007ffeefbff318  0x00000000040292a6 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff2b8:  0x000000c000250000  0x0000000000002000
0x00007ffeefbff2c8:  0x0000000000000008  0x000000000406d6c0 <runtime.walltime_trampoline+0x0000000000000000>
0x00007ffeefbff2d8:  0x00007ffeefbff320 !0x00007fff203dec9e
0x00007ffeefbff2e8: >0x00007ffeefbff320  0x0000000006c20000
0x00007ffeefbff2f8:  0x00000000000004b7  0x000000000449fdc5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff308:  0x000000000406dcff <runtime.syscall+0x000000000000001f>  0x000000c0000f9710
0x00007ffeefbff318:  0x0000000006d83160  0x000000c0000f96e0
0x00007ffeefbff328:  0x000000000406bb50 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff360
0x00007ffeefbff338:  0x00000000040105ee <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000030
0x00007ffeefbff348:  0x000000000402efe5 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x0000000006db8560
0x00007ffeefbff358:  0x0000000000000948  0x000000c0000001a0
0x00007ffeefbff368:  0x0000000004069c69 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff378:  0x0000000005e39e10  0x0000000006d82800
0x00007ffeefbff388:  0x00007ffeefbff3d0  0x0000000004069b65 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff398:  0x0000000004069b1d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x587658f, 0xc00007acc0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
```

**Pull request closed without merging**
