### PR TITLE
[several modules] Close the response body

### PR DESCRIPTION
**Pull request by dabcoder**
Follow up of #1036, also systematically close the response body in some other modules.

### CODE REVIEW

**Comment by dabcoder** [comment]
Test failure:

```
--- FAIL: TestFinnhubClient (0.60s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```

**Comment by senorprogrammer** [comment]
Are you able to resolve this failure?

**Comment by dabcoder** [comment]
> Are you able to resolve this failure?

@senorprogrammer I am not, no. Even if we close the response body at the end of the `finnhubRequest` function, the test fails with the same error. Any ideas what could be happening here?

**Comment by senorprogrammer** [comment]
That might be, I'll take a look and see if I can figure it out.

**Comment by senorprogrammer** [comment]
Looks good

**Comment by dabcoder** [comment]
Thanks for following up on that one. Did you find out what the issue was?

**Comment by senorprogrammer** [comment]
It was as you noted above, the test required a Finnhub API key. I've deleted the test here https://github.com/wtfutil/wtf/commit/9a703dd78b6737edea0d21d0f9a8ce72c2f6a8b0 since it did't add very much and ideally tests should not contact external services.

**Pull request merged**
