### PR TITLE
feat(steam): adding steam status module

### PR DESCRIPTION
**Pull request by despreston**
Adding a module that displays a list of [Steam](https://steamcommunity.com/dev) usernames and their corresponding status. I modeled this after the `twitch` module.

Steam API key is required and is provided via env var.

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Sweet! Could you provide a screenshot of it here that I can include in the documentation?

**Comment by despreston** [comment]
I was planning to update the docs in a subsequent PR. Do you mind if I do that?

**Comment by senorprogrammer** [comment]
This looks good and will be merged in once the breaking changes in master are resolved (https://github.com/wtfutil/wtf/issues/1221).

**Comment by senorprogrammer** [comment]
Nice!

**Pull request merged**
