### PR TITLE
Allow duplicates of modules

### PR DESCRIPTION
**Pull request by Seanstoppable**
This leverages the recent config changes, extending it so that config is literally using passed config, rather than
passed config value
Uses cmdRunner as an example for #181
Because config turns into a map, names are the root keys, and an optional type is provided

### CODE REVIEW

**Comment by Seanstoppable** [comment]
Deliberately keeping this small, but should be easy to flip all widgets to this methodology.

**Comment by Seanstoppable** [comment]
#419 contains most of the code to get rid of the rest of the global config coupling, which would turn this PR into just doing the 'module type' logic.

**Comment by senorprogrammer** [comment]
Apologies, I just noticed this is a new branch.

**Comment by Seanstoppable** [comment]
No worries. I am trying it out and kicking the tires for a few days myself.

**Comment by senorprogrammer** [comment]
If you use Slack, I encourage you to come join #wtfutil at https://invite.slack.golangbridge.org

**Comment by senorprogrammer** [comment]
Awesome

Screen Shot 2019-04-29 at 4 58 00 PM

**Comment by senorprogrammer** [comment]
We just have to fix widget name - the hard-coded names that were removed were in there because the display name doesn't necessarily match to the module name ("nbascores" vs. "NBA Scores" for instance).

**Comment by Seanstoppable** [comment]
Ask and ye shall receive. Now the modules define a defaultTitle, and when doing common settings, if no title is specified in the config, it uses the default. Fortuitously leverages the widget.Name -> widget.CommonSettings.Title refactor we merged the other day.

**Comment by senorprogrammer** [comment]
Sweet. I've got this built and running locally. Nice work.

**Comment by senorprogrammer** [comment]
There's a few minor things I want to fix elsewhere before this goes in, then I'll merge this one in and release as 0.9.0

**Comment by Seanstoppable** [comment]
No problem. Let me know if there is anything I can help with.

**Comment by abhayjatindoshi** [comment]
How do I get multiple cmdrunners working. I just saw the config file on [#181](https://github.com/wtfutil/wtf/issues/181) and tried to change cmdrunner as follows

```
cmdrunner_a:
    plugin: 'cmdrunner'
    name: 'A'
    ...

cmdrunner_b:
    plugin: 'cmdrunner'
    name: 'B'
    ...

cmdrunner_c:
    plugin: 'cmdrunner'
    name: 'C'
    ...

```

But I'm still getting this error
`Widget cmdrunner_a and/or type cmdrunner_a does not exist` 

Am I missing something here ?

**Comment by senorprogrammer** [comment]
Use `type`, not `plugin` in your config.

**Pull request merged**
