### PR TITLE
Add Pocket module

### PR DESCRIPTION
**Pull request by 3mard**
Hey all this add mvp module to solve #713

### CODE REVIEW

**Comment by senorprogrammer** [comment]
I'll try to get this in this weekend

**Comment by michaelMinar** [comment]
This looks amazing. Is there a little documentation on how to configure the module? I tried gleaning it from the code itself - but couldn't get it working. Thanks!

**Comment by senorprogrammer** [comment]
Yeah, https://github.com/wtfutil/wtfdocs/issues/82 has been opened to address the lack of documentation. In the meantime, something like this should work (I don't use Pocket so it might need some tweaking):

```
  pocket:
      enabled: true
      consumerKey: "[consumer key here]"
      position:
        top: 5
        left: 0
        height: 2
        width: 1
      refreshInterval: 15
```

with the `consumerKey` obtained by following these instructions https://getpocket.com/developer/docs/authentication

**Comment by 3mard** [comment]
Sorry I totally forgot to add the docs, will do them as soon as possible

**Pull request merged**
