### PR TITLE
Finnhub mod for stocks

### PR DESCRIPTION
**Pull request by applegreengrape**

### CODE REVIEW

**Comment by applegreengrape** [comment]
Screenshot 2020-10-19 at 00 40 25

**Comment by applegreengrape** [comment]
#930

**Comment by applegreengrape** [comment]
@senorprogrammer - have dug through it a couple of times. still haven't figured out why I failed at one static import check. could you please have a look? cheers

**Comment by senorprogrammer** [comment]
Pretty sure it's an ordering issue. I think it probably wants the imports in `settings.go` to look like:

```
import (
 	"os"

 	"github.com/olebedev/config"
 	"github.com/wtfutil/wtf/cfg"
 	"github.com/wtfutil/wtf/utils"
 )
```

**Comment by senorprogrammer** [comment]
Do you have `goimports` installed? In my editor it handles the arrangement of import ordering automatically (it can also be run locally).

**Comment by senorprogrammer** [comment]
Hi @applegreengrape, could you provide an example of the YAML configuration for this module?

**Comment by applegreengrape** [comment]
@senorprogrammer if it is okay, could you accept my pr? and you can point me to the documentation files, I can add the configuration :). cheers.

**Comment by senorprogrammer** [comment]
Don't worry about writing the docs, I'm happy to do that. I just need an example of the config YAML so I can see how to set this up.

**Comment by applegreengrape** [comment]
@senorprogrammer  here you go:
```
    finnhub:
      apiKey: ""
      symbols:
        - "AAPL"
        - "MSFT"
        - "AMZN"
        - "FSLY"
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 2
      refreshInterval: 5
```

**Comment by senorprogrammer** [comment]
Thanks!

**Pull request merged**
