### PR TITLE
Implemented a Grafana alerts widget

### PR DESCRIPTION
**Pull request by schoentoon**
This widget will visualize Grafana alerts and give easy access to open them in your browser. Attached is an example of how it looks like (blurred out some server details)
Screenshot_2020-10-19_18-54-17

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Hi @schoentoon, could you provide an example of the YAML configuration for this module?

**Comment by schoentoon** [comment]
Of course, I'm gonna have to hide some information though.

Assuming it's for documentation sake, probably useful to mention that an api key can be generated at <baseURL>/org/apikeys
Provided base uri is internal and will not work.
```grafana:
      enabled: true
      refreshInterval: 300
      apiKey: "<snip>"
      baseUri: "https://grafana.schoentoon.com"
      position:
        top: 1
        left: 3
        width: 2
        height: 2
```

**Comment by senorprogrammer** [comment]
This is perfect, thanks.

**Comment by senorprogrammer** [comment]
Sweet!

**Pull request merged**
